on:
  workflow_call:
    inputs:
      godot_tag:
        required: true
        type: string

      godot_version:
        required: true
        type: string

      mono_tag:
        required: true
        type: string

      steamworks_sdk_tag:
        required: true
        type: string

    secrets:
      steamworks_sdk_repo:
        required: true

      steamworks_sdk_repo_token:
        required: true


jobs:
  build-macos:
    runs-on: macos-latest

    name: Mac ${{ matrix.name }}

    env:
      SCONSFLAGS:
      STRIP: "strip -u -r"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor and Templates
            build-mono: false
            cache-name: macos

    steps:
      - uses: actions/checkout@v4

      # Download Godot to start
      - name: Download Godot
        uses: ./.github/actions/download-godot
        with:
          version: ${{ inputs.godot_tag }}

      # Download GodotSteam
      - name: Download GodotSteam
        uses: ./.github/actions/download-godotsteam

      # Download Steamworks SDK
      - name: Download Steamworks SDK
        uses: ./.github/actions/download-steamworks
        with:
          path: "steamworks"
          repository: ${{ secrets.steamworks_sdk_repo }}
          token: ${{ secrets.steamworks_sdk_repo_token }}
          ref: ${{ inputs.steamworks_sdk_tag }}

      # Download GodotSteam Multiplayer Peer
      - name: Download GodotSteam Multiplayer Peer
        uses: ./.github/actions/download-godotsteam-multiplayer
        with:
          path: "godotsteammultiplayer"

      # Mono prep
      - name: Move Shared Library For Mono
        if: ${{ matrix.build-mono }}
        uses: ./.github/actions/prep-mono
        with:
          path: "osx"
          lib: "libsteam_api.dylib"

      # Download and install Vulkan
      - name: Download Vulkan SDK
        uses: ./.github/actions/download-vulkan

      # Get that cache money
      - name: Setup Build Cache
        uses: ./.github/actions/setup-cache
        with:
          cache-name: ${{ matrix.cache-name }}
          godot-base: inputs.godot_tag
        continue-on-error: true

      # Setup Python and SCONS
      - name: Setup Python and SCONS
        uses: ./.github/actions/setup-dependencies

      # Setup Mono
      - name: Setup Mono (x86_64)
        if: ${{ matrix.build-mono }}
        uses: ./.github/actions/setup-mono
        with:
          mono-release: "osx-x86_64"
          mono-bcl: "bcl-desktop"
          mono-build-tag: ${{ inputs.mono_tag }}

      - name: Setup Mono (arm64)
        if: ${{ matrix.build-mono }}
        uses: ./.github/actions/setup-mono
        with:
          mono-release: "osx-arm64"
          mono-build-tag: ${{ inputs.mono_tag }}

      - name: Mono precompilation
        if: ${{ matrix.build-mono }}
        uses: ./.github/actions/build-godot
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} module_mono_enabled=yes mono_glue=no
          platform: macos
          target: editor

      # Generate Mono glue
      - name: Generate Mono glue code
        if: ${{ matrix.build-mono }}
        run: |
          DRI_PRIME=0 "./bin/godot.macos.editor.x86_64.mono" --generate-mono-glue modules/mono/glue

      - name: Set Mono Scons flags
        if: ${{ matrix.build-mono }}
        run: |
          echo "MONO_SCONSFLAGS=module_mono_enabled=yes mono_glue=yes copy_mono_root=yes mono_bcl=$HOME/mono-bcls/desktop-bcl/net_4_x" >> $GITHUB_ENV

      - name: Clear bin
        run: |
          rm -rf bin

      # Compiling editors
      - name: Editor compilation (arch=x86_64)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} arch=x86_64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-osx-x86_64-release' || '' }}
          platform: macos
          target: editor

      - name: Editor Compilation (arch=arm64)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} arch=arm64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-osx-arm64-release' || '' }}
          platform: macos
          target: editor

      # Create Mac Universal package
      - name: Package Editor (arch=arm64, x86_64)
        uses: ./.github/actions/prep-macos
        with:
          target: 'editor'

      - name: Upload Editor
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-editor
          path: bin/macos_editor.zip

      - name: Clear bin
        run: |
          rm -rf bin

      # Compiling templates
      - name: Debug Template Compilation (arch=x86_64, target=template_debug)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} arch=x86_64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-osx-x86_64-release' || '' }}
          platform: macos
          target: template_debug

      - name: Debug Template Compilation (arch=arm64, target=template_debug)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} arch=arm64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-osx-x86_64-release' || '' }} debug_symbols=no
          platform: macos
          target: template_debug

      - name: Release Template Compilation (arch=x86_64, target=template_release)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} arch=x86_64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-osx-arm64-release' || '' }}
          platform: macos
          target: template_release

      - name: Release template Compilation (arch=arm64, target=template_release)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ env.MONO_SCONSFLAGS }} ${{ matrix.sconsflags }} arch=arm64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-osx-arm64-release' || '' }} debug_symbols=no
          platform: macos
          target: template_release

      # Create Mac Universal package
      - name: Package Templates (arch=arm64, x86_64)
        uses: ./.github/actions/prep-macos
        with:
          target: 'templates'

      - name: Upload Mac Template App
        uses: ./.github/actions/upload-artifact
        with:
          name: macos-template-app
          path: bin/macos.zip

      - name: Clear bin
        run: |
          rm -rf bin